test_mode = 'disable'

[[backends]]
validator_path = '/scripts/godwoken-scripts/meta-contract-validator'
generator_path = '/scripts/godwoken-scripts/meta-contract-generator'
validator_script_type_hash = '0x9106daf8e99123f86a954276032e7f5e95f82bc424f3664bc8b9f4fb9e226aa2'

[[backends]]
validator_path = '/scripts/godwoken-scripts/sudt-validator'
generator_path = '/scripts/godwoken-scripts/sudt-generator'
validator_script_type_hash = '0x108af2fe9fa8df03877ac62f77584ce56a33c37b0b74b6d6b8af6b1b8a5e93ab'

[[backends]]
validator_path = '/scripts/godwoken-polyjuice/validator'
generator_path = '/scripts/godwoken-polyjuice/generator'
validator_script_type_hash = '0x1b46dee6a36e20314f35d09f8bd1c67fe5449cb67bc96603dd8a9fee4539660a'

[store]
path = ''

[genesis]
timestamp = 1625109071393
rollup_type_hash = '0x9b260161e003972c0b699939bc164cfdcfce7fd40eb9135835008dd7e09d3dae'
meta_contract_validator_type_hash = '0x9106daf8e99123f86a954276032e7f5e95f82bc424f3664bc8b9f4fb9e226aa2'

[genesis.rollup_config]
l1_sudt_script_type_hash = '0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4'
custodian_script_type_hash = '0x0315fdad192726de6683ae1a6c0b3ec1859898200320aa5724d8aefdf52137c0'
deposit_script_type_hash = '0x2ac6755ea47cd118c147f31602929212d39944cc5a49ec12f63c71459be0999a'
withdrawal_script_type_hash = '0x505faeb7287f122ee1f87318ce4c995398f4c6a42b034d9e0af0b0bdf3e1f1fe'
challenge_script_type_hash = '0xe1fb447a81d9581fa422b73bff2ad5dc570b410866353bb5a9649cc4eaa1116c'
stake_script_type_hash = '0x34d675a83c4363943c3d6c61bcf0ac86ff452c7002822961fbcf04f636c9b8db'
l2_sudt_validator_script_type_hash = '0x108af2fe9fa8df03877ac62f77584ce56a33c37b0b74b6d6b8af6b1b8a5e93ab'
burn_lock_hash = '0x0000000000000000000000000000000000000000000000000000000000000000'
required_staking_capacity = '0x5af3107a4000'
challenge_maturity_blocks = '0x1c2'
finality_blocks = '0x2710'
reward_burn_rate = '0x32'
allowed_eoa_type_hashes = [
    '0xfcf093a5f1df4037cea259d49df005e0e7258b4f63e67233eda5b376b7fd2290',
    '0x65a9638b4bb8595636a83a1f8b4288fade1fd1f2835b494af0ff88e8509d7768',
]
allowed_contract_type_hashes = [
    '0x9106daf8e99123f86a954276032e7f5e95f82bc424f3664bc8b9f4fb9e226aa2',
    '0x108af2fe9fa8df03877ac62f77584ce56a33c37b0b74b6d6b8af6b1b8a5e93ab',
    '0x1b46dee6a36e20314f35d09f8bd1c67fe5449cb67bc96603dd8a9fee4539660a',
]

[genesis.secp_data_dep]
dep_type = 'code'

[genesis.secp_data_dep.out_point]
tx_hash = '0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f'
index = '0x3'
[chain.genesis_committed_info]
number = '0x1e73fb'
block_hash = '0x01ad201ffae799ebdc5174ddd8214ea0d536724f5e73ab69cfa51f7784bc34d2'
transaction_hash = '0xb9065e6f53cb0b61b90bfe60196c172ca50b75aaa5120cb69bba7ef1bca06404'

[chain.rollup_type_script]
code_hash = '0xb6994c60b6a7207483483dfd363d9aadb1166a8ea312d7e3ed9e9df2de4073ea'
hash_type = 'type'
args = '0xc3b25c8072e78e65fed368bffd3024ee56f8260f42006e328c0545cf329d3ccf'

[rpc_client]
indexer_url = 'http://127.0.0.1:8116'
ckb_url = 'http://127.0.0.1:8114'

[rpc_server]
listen = 'localhost:8119'

[block_producer]
account_id = 0

[block_producer.rollup_cell_type_dep]
dep_type = 'code'

[block_producer.rollup_cell_type_dep.out_point]
tx_hash = '0x05847669979cf71f2fe287f923e55ac5aef79b1ca717a7156304cb0eec7ecd2b'
index = '0x0'

[block_producer.rollup_config_cell_dep]
dep_type = 'code'

[block_producer.rollup_config_cell_dep.out_point]
tx_hash = '0x8efd7be4e8bc0114a476e724b37a1ae3d72bf53da6ca49c92cc63420574c19de'
index = '0x0'

[block_producer.deposit_cell_lock_dep]
dep_type = 'code'

[block_producer.deposit_cell_lock_dep.out_point]
tx_hash = '0xa1e4f419167f1bf1b09ac75c0738bda5e6d625b29bbb41041e1a71bb4c434a49'
index = '0x0'

[block_producer.stake_cell_lock_dep]
dep_type = 'code'

[block_producer.stake_cell_lock_dep.out_point]
tx_hash = '0xffbf433007a98cdd252a97b58b98f264e0a396d89da0d06ddcbb8aaafe506f58'
index = '0x0'

[block_producer.poa_lock_dep]
dep_type = 'code'

[block_producer.poa_lock_dep.out_point]
tx_hash = '0x899767256167736ffd86470e94871f92c852f59ad33f11a695b15ee85ffd4b32'
index = '0x0'

[block_producer.poa_state_dep]
dep_type = 'code'

[block_producer.poa_state_dep.out_point]
tx_hash = '0xb9147811c6aee5d749ba1b154b31e3303bb5946c3ec4a5dadf0ed84732fd6e6c'
index = '0x0'

[block_producer.custodian_cell_lock_dep]
dep_type = 'code'

[block_producer.custodian_cell_lock_dep.out_point]
tx_hash = '0xaae50086ca57658cb08750b6e2d59380e3bc23f12fd102fcfe73cce0b7f81ec0'
index = '0x0'

[block_producer.withdrawal_cell_lock_dep]
dep_type = 'code'

[block_producer.withdrawal_cell_lock_dep.out_point]
tx_hash = '0xc9cdedb7d3ffef7c4be941edef3da85ff6dca450275b9d8a27a18a0af740c7bc'
index = '0x0'

[block_producer.l1_sudt_type_dep]
dep_type = 'code'

[block_producer.l1_sudt_type_dep.out_point]
tx_hash = '0xe12877ebd2c3c364dc46c5c992bcfaf4fee33fa13eebdf82c591fc9825aab769'
index = '0x0'

[block_producer.wallet_config]
privkey_path = '/deploy/pk'

[block_producer.wallet_config.lock]
code_hash = '0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8'
hash_type = 'type'
args = '0x016fb53e6439c433cf7c1cbf1f480a2a96618c73'
